name: Build and Deploy FHIR IG

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository and initialize submodules
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Set up Java 17 (required by IG Publisher)
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Set up Node.js for SUSHI
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Cache npm packages
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Install SUSHI globally and update $PATH
      - name: Install SUSHI and update PATH
        run: |
          npm install -g fsh-sushi
          echo "export PATH=$(npm bin -g):$PATH" >> $GITHUB_ENV
          echo "SUSHI version: $(sushi --version)"

      # Set up Ruby for Jekyll
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      # Cache Ruby gems if Gemfile.lock exists
      - name: Cache Ruby gems
        if: hashFiles('**/Gemfile.lock') != ''
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Install Jekyll and bundler
      - name: Install Jekyll
        run: gem install jekyll bundler

      # Display versions of all key tools
      - name: Verify tool versions
        run: |
          echo "Java version:"
          java -version
          echo "Node version:"
          node -v
          echo "SUSHI version:"
          sushi --version
          echo "Jekyll version:"
          jekyll --version

      # Download the IG Publisher JAR
      - name: Download IG Publisher
        run: |
          mkdir -p input-cache
          wget -O input-cache/org.hl7.fhir.publisher.jar \
            https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar

      # Run SUSHI to convert FSH to FHIR JSON
      - name: Run SUSHI
        run: |
          echo "Running SUSHI..."
          sushi .

      # Run the IG Publisher without re-running sushi
      - name: Run IG Publisher
        run: |
          echo "Running IG Publisher..."
          java -jar input-cache/org.hl7.fhir.publisher.jar -ig . --no-sushi -tx https://tx.fhir.org/r4

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
