name: Build and Deploy FHIR IG

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Ensure .gitmodules and Initialize Submodules
        run: |
          if [ -f .gitmodules ]; then
            git submodule update --init --recursive
          else
            echo ".gitmodules not found. Skipping submodule init."
          fi

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Cache Ruby gems
        if: hashFiles('**/Gemfile.lock') != ''
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install SUSHI globally
        run: |
          npm install -g fsh-sushi
          echo "$(npm bin -g)" >> $GITHUB_PATH
          export PATH="$(npm bin -g):$PATH"
          sushi --version

      - name: Install Jekyll and Bundler
        run: gem install jekyll bundler

      - name: Verify tool versions
        run: |
          java -version
          node -v
          sushi --version
          jekyll --version

      - name: Download IG Publisher
        run: |
          mkdir -p input-cache
          wget -O input-cache/org.hl7.fhir.publisher.jar \
            https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar

      - name: Run SUSHI
        run: |
          export PATH="$(npm bin -g):$PATH"
          sushi .

      - name: Run IG Publisher (with -no-sushi)
        run: |
          export PATH="$(npm bin -g):$PATH"
          java -jar input-cache/org.hl7.fhir.publisher.jar -ig . -no-sushi -tx https://tx.fhir.org/r4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
